### ISSUE TITLE
Random 500 errors

### ISSUE THREAD

**Issue by iCr** [michael-lynch/instagram-lite#13]
Hi, i`m using your script, and all was ok, but yesterday a gave an strange error, half of pictures on wall, using your script does no showing, display me me 500 error.
Here is examples:
Normal loading image (url generated by instagramLite):
https://scontent.cdninstagram.com/hphotos-xtf1/t51.2885-15/e35/1516590_1593296804253995_164126015_n.jpg
500 error image (url generated by instagramLite):
https://scontent.cdninstagram.com/hphotos-xap1/t51.2885-15/s612x612/e35/10860111_1607570656161310_708293885_n.jpg

UPD: seen your demo, half of images have same error, and does not show...

**Comment by michael-lynch** [comment]
I'm guessing Instagram was having issues on their end...
