### ISSUE TITLE
Comments not rendering

### ISSUE THREAD

**Issue by swathikeshav** [michael-lynch/instagram-lite#14]
Hi,

Is there any way to fetch the number of comments?

Swati

**Comment by swathikeshav** [comment]
Comments: true;

didnt work

**Comment by michael-lynch** [comment]
`comments` isn't a parameter the plugin expects. However, I've just added a new parameter, `comments_count`, which can be used to get the number of comments for each photo / video. The demo has been updated [here](http://michael-lynch.github.io/instagram-lite/). Have a look.

**Comment by swathikeshav** [comment]
Thanks a lot Michael!
