### ISSUE TITLE
show error on the plugin

### ISSUE THREAD

**Issue by himelkazi** [michael-lynch/instagram-lite#17]
I initialize the plugin from an annonyms function. But it show "Uncaught TypeError: Cannot read property 'length' of undefined"

(function ($) {

		jQuery(document).ready(function() {
			$('.instagram-lite').instagramLite({
			    clientID: '15100008ec574cceae4c95c45ffeb9fe',
			    username: 'thevelvetstreet',
		    	urls: true,
				limit: 8,
				captions: true,
				likes: true,
				comments_count: true
			});
		}); // ready()

		
})(jQuery)

**Comment by gopinathpara** [comment]
I'm facing this same issue. Any help?

**Comment by alexcampillo** [comment]
I get this error whenever I use a static site generator, specifically Jekyll. Works great on other sites though. Not sure what the problem is but that's the only difference I can spot between the sites it works on and the ones it doesn't.

**Comment by bearded12** [comment]
I'm running into this issue as well. Any help would be appreciated.

**Comment by michael-lynch** [comment]
@himelkazi I tested your `clientID` and I got this error:

`The access_token provided is invalid.`

I think you need a new client ID.

**Comment by acamou** [comment]
Does the script have a problem with requesting to sandbox apps?
I have tried different client ids and username and everything seems to be setup right but I always get "The access_token provided is invalid."  I see in the network requests that the username and client are being sent but I always get the same error.

**Comment by michael-lynch** [comment]
Unfortunately this plugin is no longer usable. Please see the updated readme for more information.
