### ISSUE TITLE
Using hashtags and load more fetches duplicates

### ISSUE THREAD

**Issue by rawksteady** [michael-lynch/instagram-lite#19]
I'm not quite sure where this is going wrong, but every now and then when fetching images via hashtag, when loading more photos it seems to print out duplicates.

Example: I display and fetch 10 images via from a hashtag, when loading more images I keep getting the same 10 images.

**Comment by michael-lynch** [comment]
`A simple, lightweight jQuery plugin used to display a user's Instagram photos.` 

This plugin fetches images by user, not by hashtag, but I may add that in as a feature at some point.
