### ISSUE TITLE
Not showing corrently

### ISSUE THREAD

**Issue by hannahblair** [michael-lynch/instagram-lite#20]
Hiya, I'm running the demo from my local host using the local downloaded version of this plugin, but it's showing up as seen on the screenshot below.

![isntascrnsht](https://cloud.githubusercontent.com/assets/15165908/13732586/f9ebec8e-e97d-11e5-9a39-c34aa9e43285.png)
 
Why is this? The link on the readme.md file shows the desired result but it's not at all what I expect when I run from the downloaded code.

Thanks in advance!

**Comment by michael-lynch** [comment]
Unfortunately this plugin is no longer usable. Please see the updated readme for more information.
