### ISSUE TITLE
caption length

### ISSUE THREAD

**Issue by FaiqAdam** [michael-lynch/instagram-lite#22]
How to limit caption text?

**Comment by michael-lynch** [comment]
Right now the plugin only displays the full caption, but I'll consider adding a slice function to the plugin if I have time. For now, you could slice the text after the plugin has succeeded:

```
success: function() {
    var captionLength = 20,
          caption = $('.il-photo__caption').text(),
          newCaption = caption.slice(0, captionLength);

    $('.il-photo__caption').html(newCaption);
}
```
This would limit the caption to 20 characters.

**Comment by CydGoblin** [comment]
The above will repeat the same caption in every picture. In case is worth something to anyone here is mine. Change the id to yours.
```
success: function() {
    var captionLength = 180;
    $('#instagram .il-item').each(function(i, obj) {
        var caption = $(this).find('.il-photo__caption').text(),
            newCaption = caption.slice(0, captionLength);
        $(this).find('.il-photo__caption').html(newCaption);
    });
}
````
