### ISSUE TITLE
loadMore Setting Missing/Not Working

### ISSUE THREAD

**Issue by jdorenbush** [michael-lynch/instagram-lite#23]
I used the loadMore setting in the previous version of this plugin, but I can't get it to work in the latest version. After looking at both versions of JS,  it's clear that a lot has changed from the previous version, and in terms of the loadMore setting, there is no sign of it in the new one. 

Based on the ReadMe file though, it sounds like the setting should be or was intended on being available: "An integer that indicates the amount of photos to be returned. If loadMore is set, the limit property will determine how many photos are loaded each time. (default: 10)."

Any help is appreciated. Cheers!

**Comment by michael-lynch** [comment]
Ah, the docs need to be updated. Good catch, and sorry about that. The API only allows you to display a maximum of 20 pieces of media, so the `loadMore` option is now unfortunately obsolete. I will keep the `limit` option but I may need to update the plugin. Obviously it will only allow an integer from 1-20.
