### ISSUE TITLE
Is it safe to reveal access token in js?

### ISSUE THREAD

**Issue by waqasy** [michael-lynch/instagram-lite#24]
Just curious! normally access tokens are meant to keep secret but in this case we're putting it in js file. Does it use read-only token?

**Comment by michael-lynch** [comment]
Exposing your access token shouldn't be a problem. Instagram has provided an implicit authentication flow exactly for this reason - so we can use access tokens client side. Remember, you can only use the API to retrieve media from your own account or an account that has been approved. It's your `Client ID` and `Client Secret` that you'll want to keep hidden.
