### ISSUE TITLE
Tall Videos mis

### ISSUE THREAD

**Issue by CarlowSEO** [michael-lynch/instagram-lite#26]
When viewing a video that is tall and narrow (now that all video's aren't square) it is misaligning

See example - http://paintball-revolution.myshopify.com/?preview_theme_id=193957064

**Comment by michael-lynch** [comment]
The plugin is only meant to add the images and videos to the DOM as they were originally created. To be consistent, you'd either have to upload media that is all the same size, or use CSS to style the elements however you like.
