### ISSUE TITLE
Inverted comma missing

### ISSUE THREAD

**Issue by gabrielsomi** [michael-lynch/instagram-lite#29]
Hey, guys! @michael-lynch :)
Thank you for your awesome plugin.
I've just detected an error on line 157, where there is an inverted comma missing on the data-instagram attribute, avoiding the link to be processed correctly.
**This is your original line**
> item = `<li class="il-item" data-instagram-id="${thisMedia.id}>${item}</li>`;

**And this is the corrected one**
> item = `<li class="il-item" data-instagram-id="${thisMedia.id}">${item}</li>`;

Cheers!

**Comment by michael-lynch** [comment]
Good catch! Thanks!
