### ISSUE TITLE
Allow for custom layouts

### ISSUE THREAD

**Issue by Cam** [michael-lynch/instagram-lite#7]
Hi. LOVE the plugin so far. Any chance you could allow for customised layouts? Using this in frameworks and existing grid structures could be much easier (and much more elegant) with other layout options (other than a simple list). The ability to create a custom template as a variable would be awesome. This has been done well on Instafeed.js, for example.

**Comment by michael-lynch** [comment]
I hesitate to add a templating system, only because I want to keep this as lightweight as possible, but I do really like the concept. If I have some time, I may try out some kind of solution. Thanks for the suggestion!

**Comment by Cam** [comment]
Hi @michael-lynch. Totally know what you mean. The other day I was thinking about this and thought of a slightly lateral option. You could potentially target the first child of the div/list for repetition, that you are targeting in the JS. That way you would be allowing for any kind of (2 level) structure, which should cover list, flex and basic column structures.

Anyway... just an idea.

**Comment by Cam** [comment]
Eg:
`<div id="instagram-lite flex">
    <div class="instagram-item-container"></div>
</div>

$('.instagram-lite').instagramLite({
});`

**Comment by Yako75** [comment]
Hello I have a simple solution to this problem
edit file instagramLite.js line 83

`item = '<div class="col-xs-6 col-sm-6 col-sm-6 col-lg-6" style="padding:0 10px 10px 0"><img style="border:1px solid #fff;" class="img-responsive" src="'+thisMedia.images.standard_resolution.url+'" alt="Instagram Image" data-filter="'+thisMedia.filter+'" /></div>';`


Inserted Bootstrap grid but you can insert your own grid and found perfect.

Hope this can help you! @Cam

**Comment by Cam** [comment]
@Yako75 good call! Simple enough for me :) Thanks!
